# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a88d9189ada0a35b69bc3b2193cd308dac29d4e1f523a08d17b9320237ad28fd1ae8b2f892468d4a6f8558da2f9e871630aaf4c0e5a185ab1c87671c87f0012f

test:
  secret_key_base: ab181d2dcaa48fb8129281bc5f7a31c143bb7cdcf7bbe9f49ffe09469fd3af6d6c262f9cd5a6f9115c9c86a6a4ed98419ba9fe268fe6558f741d77cd00ee69e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
